# This file is managed by Centy. Use the Centy CLI to modify it.
name: Microtask
identifier: uuid
features:
  displayNumber: true
  status: true
  priority: true
  softDelete: false
  assets: false
  orgSync: false
  move: true
  duplicate: true
statuses:
- todo
- in-progress
- done
- skipped
defaultStatus: todo
priorityLevels: 2
